version: "3"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    container_name: cache

  weblate:
    image: weblate/weblate:latest
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - WEBLATE_ADMIN_EMAIL=${WEBLATE_ADMIN_EMAIL}
      - WEBLATE_ADMIN_PASSWORD=${WEBLATE_ADMIN_PASSWORD}

      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

      - WEBLATE_HOST=0.0.0.0
      - WEBLATE_SITE_DOMAIN=${WEBLATE_SITE_DOMAIN}
      - WEBLATE_REDIS_URL=redis://cache:6379/0

      - WEBLATE_EMAIL_HOST=${WEBLATE_EMAIL_HOST}
      - WEBLATE_EMAIL_PORT=${WEBLATE_EMAIL_PORT}
      - WEBLATE_EMAIL_HOST_USER=${WEBLATE_EMAIL_HOST_USER}
      - WEBLATE_EMAIL_HOST_PASSWORD=${WEBLATE_EMAIL_HOST_PASSWORD}
      - WEBLATE_SERVER_EMAIL=${WEBLATE_SERVER_EMAIL}
      - WEBLATE_DEFAULT_FROM_EMAIL=${WEBLATE_DEFAULT_FROM_EMAIL}
      - WEBLATE_REGISTRATION_CAPTCHA=${WEBLATE_REGISTRATION_CAPTCHA}

    volumes:
      # Volumen para los datos internos de Weblate
      - weblate_data:/app/data

      # Montar la carpeta "GISWATER.GITHUB.IO.DOCS" (que está un nivel arriba de "weblate/")
      - ../:/repos/docs:rw

volumes:
  db_data:
  weblate_data:
